### ISSUE TITLE
Images are not displayed

### ISSUE THREAD

**Issue by pavlo-o-savchuk** [maherzaidoune/react-native-url-preview#18]
Try putting an image url like that, or any other working image URL. 
` <UrlPreview text="https://i.picsum.photos/id/630/200/300.jpg" />`

Instead of an image preview you will see container with the background. 
I checked on the code. There is an error of getting image URL link from array of data.images.

**Comment by maherzaidoune** [comment]
this is not an image viewer package, try  [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image),
react-native-url-preview use the meta data of the given website to display a preview for it.
