### ISSUE TITLE
LinkPreviewError

### ISSUE THREAD

**Issue by NicholasIoanJones** [maherzaidoune/react-native-url-preview#20]
I'm honestly not sure if this is an issue with RNUrlPreview but in the latest build of our app some link previews were not rendering and on inspection we were getting LinkPreviewError logged in the console for those urls which then don't render the preview.

"github.com" works
"https://www.google.com" fails
"www.google.com" works on Android, fails on iOS
"omnilife.ai" fails
"www.omnilife.ai" works

To diagnose I regressed back to our last release branch and rebuilt the app - with the same failures as above, yet our live app works.

The only difference that I can see therefore is that both xcode and Android studio have both upgraded. I may be clutching at straws, but could there be an issue with your library and xcode 11.4.1?

**Comment by maherzaidoune** [comment]
this plugin is purely js, so the version of Xcode should not affect it

**Comment by NicholasIoanJones** [comment]
Thanks for your response @maherzaidoune, I thought I may be clutching at straws

**Comment by maherzaidoune** [comment]
I'll test those websites specifically to find out what's wrong
