### ISSUE TITLE
When placing react native url preview in a flatlist it causes a massive memory leak

### ISSUE THREAD

**Issue by lanceylexima** [maherzaidoune/react-native-url-preview#21]
When you place a react native url preview within a flatlist, a memory leak occurs that will end up crashing your app.

**Comment by maherzaidoune** [comment]
I'll try to reproduce that problem

**Comment by maherzaidoune** [comment]
> When you place a react native url preview within a flatlist, a memory leak occurs that will end up crashing your app.

Hello, can you provide an example of that problem? a repo with that will be helpful  😄

**Comment by RahulRijhwani** [comment]
@maherzaidoune  Any solution I am also facing this issue

**Comment by jackvial** [comment]
I'm seeing this issue too.

**Comment by jackvial** [comment]
The leak appears to be caused by the logic in componentDidUpdate:
```
  componentDidUpdate(nextProps) {
    if (nextProps.text !== null) {
      this.getPreview(nextProps.text);
    } else {
      this.setState({isUri: false});
    }
  }
```

Not sure exactly what the issue is but I'm sure this is where the problem is. Going to look into it more later. Will post my findings.

**Comment by maherzaidoune** [comment]
> The leak appears to be caused by the logic in componentDidUpdate:
> 
> ```
>   componentDidUpdate(nextProps) {
>     if (nextProps.text !== null) {
>       this.getPreview(nextProps.text);
>     } else {
>       this.setState({isUri: false});
>     }
>   }
> ```
> 
> Not sure exactly what the issue is but the `nextProps.text !== null` comparison seems wrong and that it will call getPreview even if the next has not changed. Going to look into it more later. Will post my findings.

yes, that will lead to unnecessary updates, I tried to update that. can you try the newer version
