### ISSUE TITLE
Feature Request: support for closing url previews

### ISSUE THREAD

**Issue by sam1463** [maherzaidoune/react-native-url-preview#22]
Hi, really appreciate this library! I'm using it to render url previews in a chat, and I would like to support "close preview" functionality, where a preview is rendered, but if the user presses a close button, it would hide the preview for the remainder of the time that the component is mounted.

I have two ideas for how to do this, but both would require changes to this library, so wanted to get feedback on whether you'd have a preference, so I can try to implement one and open a PR.

1. Update this library to accept callback props like `onLoad` and `onError` which would be called when the info is successfully retrieved to render the preview, or if that fails, respectively. These could be used by consumers of this library to listen for when the preview is ready (or if getting the preview failed), and then render their own "close" button and stop rendering the url-preview component if it's pressed. Without these listeners, I could still render my own "close" button to hide the preview, but I won't know whether the preview is even rendering, so it would end up looking weird having just a "close preview" button without a preview present 😄 
2. Add the functionality for closing previews directly to this library. Could just be an "X" icon in the top right that updates component state to hide the preview when it's pressed, and maybe support for passing in a custom button as a prop.

I would be happy to do either (or both) and open a PR, but wanted to get feedback first. Let me know what you think!

**Comment by maherzaidoune** [comment]
> Hi, really appreciate this library! I'm using it to render url previews in a chat, and I would like to support "close preview" functionality, where a preview is rendered, but if the user presses a close button, it would hide the preview for the remainder of the time that the component is mounted.
> 
> I have two ideas for how to do this, but both would require changes to this library, so wanted to get feedback on whether you'd have a preference, so I can try to implement one and open a PR.
> 
> 1. Update this library to accept callback props like `onLoad` and `onError` which would be called when the info is successfully retrieved to render the preview, or if that fails, respectively. These could be used by consumers of this library to listen for when the preview is ready (or if getting the preview failed), and then render their own "close" button and stop rendering the url-preview component if it's pressed. Without these listeners, I could still render my own "close" button to hide the preview, but I won't know whether the preview is even rendering, so it would end up looking weird having just a "close preview" button without a preview present 😄
> 2. Add the functionality for closing previews directly to this library. Could just be an "X" icon in the top right that updates component state to hide the preview when it's pressed, and maybe support for passing in a custom button as a prop.
> 
> I would be happy to do either (or both) and open a PR, but wanted to get feedback first. Let me know what you think!

Hello, I'm glad you appreciate react-native-url-preview. The callbacks idea looks awesome 😄 , I'll be thankful if you implement it. 
the second point is helpful for certain cases, make sure the user can activate or hide that button, can customize its action, and customize the rendered component too.
Happy coding  😄
Waiting for your RP
Thank you.
