### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by khoitruongg** [maherzaidoune/react-native-url-preview#26]
Hi, i use a simple case like your example but getting error when loading
I'm using React Native version 0.61.5
"Attempt to invoke interface method 'java.lang.String com.facebook.react.bridge.ReadableMap.getString(java.lang.String)' on a null object reference"

**Comment by mir1198yusuf** [comment]
worked for me.
did you passed empty string ?

**Comment by maherzaidoune** [comment]
hey @khoitruongg, your issue seems to have no relation with the package itself, I hope everything works well for you now.
