### ISSUE TITLE
Google url looks weird

### ISSUE THREAD

**Issue by franjorub** [maherzaidoune/react-native-url-preview#5]
Hi the library works excellent and looks so good but we have a problem with https://google.com

normal url: 
![imagen](https://user-images.githubusercontent.com/24401350/67130455-50585000-f1cf-11e9-8e13-c1eefdbcac60.png)

google:
![imagen](https://user-images.githubusercontent.com/24401350/67130470-5bab7b80-f1cf-11e9-8d01-595caf2e0f0c.png)

what could happen ?

greetings

**Comment by maherzaidoune** [comment]
fixed in 1.1

**Comment by maherzaidoune** [comment]
for google.com , there is no enough information extracted from the url , just fixed the image resize mode, it now show the full logo image
